[package]
name = "makepress-lib"
version = "1.0.0"
edition = "2018"
publish = ["makepress"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
futures = "0.3.18"
pin-project-lite = "0.2.7"
serde = {version = "1.0.130", features = ["derive"]}
thiserror = "1.0.30"
warp = "0.3.2"
