[profile.release]
debug = 1
incremental = true
lto = "off"

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
]

[registries]
makepress = { index = "https://github.com/makepress/crates.git" }
